version: '3.8'

services:
  h2:
    image: oscarh/h2
    container_name: h2_database
    ports:
      - "8082:8082"  # Port pour l'interface web H2
      - "1521:1521"  # Port pour la connexion JDBC
    environment:
      H2_OPTIONS: "-tcpAllowOthers"  # Permet les connexions TCP externes
    volumes:
      - h2_data:/opt/h2-data  # Volume pour persister les données

volumes:
  h2_data: